# Generated by Django 5.2.3 on 2026-02-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
