# Generated by Django 5.2.3 on 2026-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organizationmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='storage_limit',
            field=models.BigIntegerField(blank=True, help_text='Value in bytes.', null=True),
        ),
    ]
