# Generated by Django 5.2.3 on 2026-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userloginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
