# Generated by Django 5.2.3 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_storage_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='file_size_lmt',
            field=models.BigIntegerField(blank=True, help_text='Value in bytes. Leave empty if no limit', null=True),
        ),
    ]
