# Generated by Django 5.2.3 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_file_size_lmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='storage_limit',
            field=models.BigIntegerField(blank=True, help_text='Value in bytes. Leave empty if no limit', null=True),
        ),
    ]
