# Generated by Django 5.2.3 on 2026-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organization_storage_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='access',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
