# Generated by Django 5.2.3 on 2026-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_organizationmember_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='role',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
