# Generated by Django 5.2.3 on 2026-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organizationmember_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='VIS', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
