# Generated by Django 5.2.3 on 2026-02-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='can_share',
            field=models.BooleanField(default=False),
        ),
    ]
