# Generated by Django 5.2.3 on 2026-02-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
