# Generated by Django 5.2.3 on 2026-02-21 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organizationmember_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='org_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
