# Generated by Django 5.2.3 on 2026-02-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
