# Generated by Django 5.2.3 on 2026-01-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
