# Generated by Django 5.2.3 on 2026-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
