# Generated by Django 5.2.3 on 2026-02-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_storage_limit'),
        ('storageapp', '0002_alter_cloudfile_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.organization'),
        ),
    ]
