# Generated by Django 5.2.3 on 2026-02-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organization_storage_limit'),
        ('storageapp', '0003_cloudfile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfiles', to='accounts.organization'),
        ),
    ]
