# Generated by Django 5.2.3 on 2026-02-20 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_organization_storage_limit'),
        ('storageapp', '0004_uploadhistory_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('failure_reason', models.CharField(blank=True, choices=[('STORAGE_FULL', 'Storage full'), ('FILE_TOO_LARGE', 'File too large'), ('CLOUDINARY_LIMIT', 'Cloudinary limit'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown error'), ('PLAN_ERROR', 'Plan error')], max_length=50, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadfiles', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UploadHistory',
        ),
    ]
