# Generated by Django 5.2.3 on 2026-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0004_remove_storedfile_folder_remove_storedfile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='cloudfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='cloudfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='cloudfile',
            name='title',
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='test_folder/'),
        ),
    ]
