# Generated by Django 5.2.3 on 2026-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0005_filehistory_delete_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='failure_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
