# Generated by Django 5.2.3 on 2026-01-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0005_remove_cloudfile_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='uploaded_file',
            field=models.FileField(upload_to='test_folder/'),
        ),
    ]
