# Generated by Django 5.2.3 on 2026-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0006_alter_cloudfile_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='file_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
