# Generated by Django 5.2.3 on 2026-02-20 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0006_filehistory_failure_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehistory',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('STORAGE_FULL', 'Storage full'), ('FILE_TOO_LARGE', 'File too large'), ('CLOUDINARY_LIMIT', 'Cloudinary limit'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown error'), ('PLAN_ERROR', 'Plan error'), ('Permission_NOT_GIVEN', 'Permission not given')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('denied', 'Denied')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
