# Generated by Django 5.2.3 on 2026-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0007_cloudfile_file_name_cloudfile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
