# Generated by Django 5.2.3 on 2026-02-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0007_alter_filehistory_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehistory',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('access', 'Access'), ('trash', 'Trash'), ('restore', 'Restore'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('share', 'Share')], default='update', max_length=15),
            preserve_default=False,
        ),
    ]
