# Generated by Django 5.2.3 on 2026-02-21 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_organizationmember_organization_and_more'),
        ('storageapp', '0008_filehistory_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploadfiles', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_entries', to='storageapp.cloudfile'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
