# Generated by Django 5.2.3 on 2026-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0008_cloudfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(),
        ),
    ]
