# Generated by Django 5.2.3 on 2026-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0009_alter_cloudfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='file_size',
            field=models.BigIntegerField(),
        ),
    ]
