# Generated by Django 5.2.3 on 2026-02-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0009_alter_cloudfile_organization_alter_cloudfile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehistory',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('access', 'Access'), ('trash', 'Trash'), ('restore', 'Restore'), ('delete', 'Delete'), ('view', 'View'), ('download', 'Download'), ('share', 'Share'), ('cancel', 'Cancel')], max_length=15),
        ),
    ]
