# Generated by Django 5.2.3 on 2026-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0010_alter_cloudfile_file_name_alter_cloudfile_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='uploaded_file',
            field=models.FileField(upload_to='cloud/'),
        ),
    ]
