# Generated by Django 5.2.3 on 2026-01-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0011_remove_cloudfile_file_url_cloudfile_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=20),
        ),
    ]
