# Generated by Django 5.2.3 on 2026-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0012_alter_cloudfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
