# Generated by Django 5.2.3 on 2026-01-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0013_cloudfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='public_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
