# Generated by Django 5.2.3 on 2026-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0014_cloudfile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cloudfile',
            name='public_id',
            field=models.CharField(max_length=255),
        ),
    ]
