# Generated by Django 5.2.3 on 2026-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0015_alter_cloudfile_file_url_alter_cloudfile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
