# Generated by Django 5.2.3 on 2026-01-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0016_cloudfile_deleted_at_cloudfile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
