# Generated by Django 5.2.3 on 2026-01-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0017_alter_cloudfile_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='cloudfile',
            name='uploaded_file',
        ),
    ]
