# Generated by Django 5.2.3 on 2026-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0018_remove_cloudfile_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='public_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cloudfile',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='cloud/'),
        ),
    ]
