# Generated by Django 5.2.3 on 2026-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0021_uploadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=10),
        ),
    ]
