# Generated by Django 5.2.3 on 2026-02-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0022_alter_uploadhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudfile',
            name='uploaded_file',
        ),
    ]
