# Generated by Django 5.2.3 on 2026-02-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_payment_plan_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
