# Generated by Django 5.2.3 on 2026-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
