# Generated by Django 5.2.3 on 2026-01-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='file_size_lmt',
            field=models.BigIntegerField(null=True),
        ),
    ]
