# Generated by Django 5.2.3 on 2026-01-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_file_size_lmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='file_size_lmt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
