# Generated by Django 5.2.3 on 2026-01-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_plan_file_size_lmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='file_size_lmt',
            field=models.BigIntegerField(blank=True, help_text='Value in bytes. Leave empty if no limit', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='storage_limit',
            field=models.BigIntegerField(blank=True, help_text='Value in bytes.', null=True),
        ),
    ]
